name: Publish

on: [push, pull_request]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x

    - name: Pack
      run: >-
        dotnet build PrismSharp.RegExCompiler/PrismSharp.RegExCompiler.csproj --configuration Release;

        dotnet build PrismSharp.RegExProvider/PrismSharp.RegExProvider.csproj --configuration Release;

        mkdir regex;
        mkdir -p regex/netstandard2.0;
        mkdir -p regex/net45;
        mkdir -p regex/net8.0;
        mkdir -p regex/net9.0;
        dotnet run --project PrismSharp.RegExProvider/PrismSharp.RegExProvider.csproj --configuration Release -f net9.0 -- "$PWD/regex/netstandard2.0" netstandard2.0;
        dotnet run --project PrismSharp.RegExProvider/PrismSharp.RegExProvider.csproj --configuration Release -f net9.0 -- "$PWD/regex/net45" net45;
        dotnet run --project PrismSharp.RegExProvider/PrismSharp.RegExProvider.csproj --configuration Release -f net8.0 -- "$PWD/regex/net8.0" net8.0;
        dotnet run --project PrismSharp.RegExProvider/PrismSharp.RegExProvider.csproj --configuration Release -f net9.0 -- "$PWD/regex/net9.0" net9.0;

        dotnet build PrismSharp.SourceGenerator/PrismSharp.SourceGenerator.csproj --configuration Release;
        dotnet build PrismSharp.Core/PrismSharp.Core.csproj --configuration Release;

        dotnet pack PrismSharp.Core/PrismSharp.Core.csproj --configuration Release -o "./packages";
      shell: pwsh

    - uses: actions/upload-artifact@v4
      with:
        name: packages
        path: "./packages"
        

  publish:
    runs-on: ubuntu-latest
    depends-on: ["build"]
    - uses: actions/download-artifact@v4
      with:
        name: packages
    
    - name: Push to NuGet
      run: dotnet nuget push "./packages/*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://www.nuget.org
      shell: pwsh

    - name: Push to GPR
      run: |
           for f in ./packages/*.nupkg
           do
             curl -vX PUT -u "vslee:${{secrets.GITHUB_TOKEN}}" -F package=@$f https://nuget.pkg.github.com/BUTR/
           done
      shell: bash

